version: '3'

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password

  webapp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    tty: true
    restart: always
    depends_on:
      - mysql_db
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=root
      - MYSQL_PASS=root
      